### ISSUE TITLE
Checksum Mismatch

### ISSUE THREAD

**Issue by medicpip** [webmin/webmin.com#1]
The webmin.com website is still directing the download of webmin to sourceforge for the version 2.013 release. This is creating an incorrect checksum compared with the website. I am assuming that the checksum listed is for the new release as I can compute it when I obtain the download link from github. *All caches have been cleared on my end to ensure this is not a user-specific issue.

**Comment by iliaross** [comment]
This issue will auto resolve within next 24 h. Sorry about that
