### ISSUE TITLE
使用webmin，command shell 执行docker logs -f 容器id，Cannot establish connection to the host.

### ISSUE THREAD

**Issue by SuperZedLv** [webmin/webmin.com#14]
使用webmin，command shell 执行docker logs -f 容器id，Cannot establish connection to the host.
![image](https://github.com/webmin/webmin.com/assets/29818685/f9a38b2c-7daa-4531-b4ec-074b2e745854)
但是ssh直接连接执行docker logs -f 容器id 是正常的

**Comment by jcameron** [comment]
Isn't that error coming from the `docker logs` command?

**Comment by SuperZedLv** [comment]
> Isn't that error coming from the `docker logs` command?

no，不使用webmin的command shell，没有这个问题，是正常的

**Comment by jcameron** [comment]
Odd, this works fine for me ...

**Comment by SuperZedLv** [comment]
![image](https://github.com/webmin/webmin.com/assets/29818685/81475072-574a-496b-bd5c-fbb8c88b21c7)
sheng升级版本使用terminal没有问题
