### ISSUE TITLE
Clarify how to install the download files

### ISSUE THREAD

**Issue by marktnz1** [webmin/webmin.com#15]
https://webmin.com/cloudmin/

The above link states the following but does not explain exactly  where to put the install file.  Ideally there there should be a curl command on this page that will users can run to install the script.  Instead "Downloaded install script, once you have it on the Linux system you want to run Cloudmin on" is too vague (also spelling mistakes on page)

"Downloads

[rpm-xen](http://cloudmin.virtualmin.com/gpl/scripts/cloudmin-gpl-redhat-install.sh) | [rpm-kvm](http://cloudmin.virtualmin.com/gpl/scripts/cloudmin-kvm-redhat-install.sh) — Red Hat Enterprise Linux, Alma, Rocky, Oracle, Fedora

[deb-xen](http://cloudmin.virtualmin.com/gpl/scripts/cloudmin-gpl-debian-install.sh) | [deb-kvm](http://cloudmin.virtualmin.com/gpl/scripts/cloudmin-kvm-debian-install.sh) — Debian and Ubuntu

Downloaded install script, once you have it on the Linux system you want to run Cloudmin on, can be executed with the folowing command:"

EVEN Better,

Is to allow users to install cloudmin from webmin ... should be boldly shown as a webmin addon.

**Comment by jcameron** [comment]
I suppose we could do that ... but I do feel a bit nervous about recommending curl commands that pipe into bash.

What spelling mistakes are there though?

**Comment by marktnz1** [comment]
Thanks. "Folowing" , "Download" not "Downloaded". 

Appreciate that... Definitely should be in everyones interest inc webmins to be easily able to install cloudmin from webmin or from terminal.

**Comment by iliaross** [comment]
> Thanks. "Folowing" , "Download" not "Downloaded".

Thanks for the heads up! The patch for the phrase is here https://github.com/webmin/webmin.com/commit/34ed9a727ecaa799ff76f49e95f86616db56dd55.
