### ISSUE TITLE
mysql backup restore table issue

### ISSUE THREAD

**Issue by KO81** [webmin/webmin.com#16]
i use to backup new tables. just in case a table runs out space and i need to make an another one.  field names and their types are copied correctly, but 'allow nulls' is set to yes, and the 'default value' is set to null, even though the backuped table has the 'allow nulls' set to false and the 'default value' is set to empty string.

**Comment by iliaross** [comment]
Hi,

Webmin uses `mysqldump` command to create dumps. If your original table explicitly defined columns to be `NOT NULL` and/or have a `DEFAULT` value other than `NULL`, these would be reflected in the `mysqldump` output.

For a column that is supposed to be `NOT NULL` with an empty string as the default, the `CREATE TABLE` part should look something like this:

```
`column_name` VARCHAR(255) NOT NULL DEFAULT ''
```

If you have more questions, please consider posting them in our [forum](https://forum.virtualmin.com/), as this is primarily a bug tracker!
