### ISSUE TITLE
page date stamp needs updating

### ISSUE THREAD

**Issue by verne-work** [webmin/webmin.com#17]
at the top of this page it has

`January 13, 2023 `

but I believe this page has been updated since then.

**Comment by jcameron** [comment]
Wait which page is this?

**Comment by iliaross** [comment]
There is only one page with this date that we have on _webmin.com_, which is `security.md`. I will fix that and also will add dates to each event.

**Comment by iliaross** [comment]
This has been fixed. Thanks for the heads up!

Jamie, please rebuild _webmin.com_.

**Comment by jcameron** [comment]
Done!
