### ISSUE TITLE
DHCP Server - Hosts and Host Groups

### ISSUE THREAD

**Issue by jmendes84** [webmin/webmin.com#18]
Hi, Is it possible to have in the DHCP Server Section Under Host and Host Groups a seperate column for descriptions? If not is this something that can be introduced in a next release? It helps to be able to see the Host Name and Host Descriptions Side by Side along with the Hardware Addess and Hostname/IP.

**Comment by jcameron** [comment]
Have you tried changing the "Show other object descriptions instead of names?" option on the configuration page of the DHCP module?

**Comment by jmendes84** [comment]
Yes I have but then that get's rid of the Host Name. I would like for both to show up in seperate columns.

**Comment by jcameron** [comment]
Ok, look for this in the next Webmin release!
