### ISSUE TITLE
Terminal page - update note

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin.com#19]
I will learn how to to fork etc.. very soon, so please don't think I am being lazy with this one. 😄 

### the issue

on the page `https://webmin.com/docs/modules/terminal/` there is this blockquote and using the information I could not find the `Enforce sudo-only privileges` option.

I got help from the forum `https://forum.virtualmin.com/t/terminal-cannot-find-enforce-sudo-only-privileges-option/128750`

I found the directions confusing for the following reasons

1. I followed the instructions to `Webmin --> Webmin Users root: Edit Webmin User` but then because on that page I could not find `Terminal: Module Access Control` I assumed because of the slash there was another location that was not present on my version of Virtualmin
1. I did not know `terminal` was clickable. ☹️ 

### proposed solution

Can you update the blockquote as follows so it is more logical.

> Starting with Webmin 2.200, all _sudo_-capable users will log in as themselves instead of as _root_. To disable this limitation, go to **Webmin ⇾ Webmin Users ⇾ root: Edit Webmin User ⇾ Available Webmin Modules ⇾ Tools ⇾ Terminal: Module Access Control** page, and set the **Enforce _sudo_-only privileges** option to **No**."

- I have removed the slash
- I have added 2 steps to the path

**Comment by iliaross** [comment]
Thanks for the heads up! It was fixed with this https://github.com/webmin/webmin.com/commit/4a8bd434274afa5e991f9aa3af5c9705cc9bcc37 commit.

It will become available online whenever Jamie rebuilds `webmin.com` site.

**Comment by shoulders** [comment]
Sounds fair 😄 , as ever I appreciate the quick fixes.
