### ISSUE TITLE
The Suggest Change link in https://webmin.dev/docs/ gives 404 error

### ISSUE THREAD

**Issue by kitatek** [webmin/webmin.com#2]
Hi,

Very happy to suggest changes to the documentation on the website, but the Suggest Changes link goes 404.

I guess PR are now on Github, but fixing the link to a proper readme would help getting more contributors.

**Comment by iliaross** [comment]
Hello,

Thanks for the heads up! However, which page exactly when clicked **Suggest Changes** returns 404?

**Comment by kitatek** [comment]
> 

The page from the URL in this issue title:  https://webmin.dev/docs/ 

It has a Suggest Change link on teh top, that points to  https://github.com/webmin/webmin.com/tree/main/content/docs/_index.md  , which gives 404 ...

**Comment by iliaross** [comment]
This is a devel version of _webmin.com_ website. It is not yet available for public.

Anyway, what would you like to change?
