### ISSUE TITLE
Creating Modules page - Improvements

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin.com#20]
### The page

https://webmin.com/docs/development/creating-modules/

### The issues
- **Suggest Changes** still points to `master` and not `main`
- The following line needs the word **'line'** changing to **'value'** because the word root can also imply the first line which is where I was looking, but we are looking for a `value` rather than a line.

https://github.com/webmin/webmin.com/blob/b5607f48932c2b6b1d9144908c4988c3e3f610d1/content/docs/Development/creating-modules.md?plain=1#L26-L26

-->

You can find this base directory by looking at the `root` value in your `/etc/webmin/miniserv.conf` file. It will differ depending on which operating system Webmin is installed.

### Additional

I am not a Linux expert, but are these locations still valid for Webmin:

Every module has its own directory under the Webmin base directory, in which all the module's CGI programs and configuration files must be stored. For example, if the Webmin base was `/usr/libexec/webmin`, a module called foobar would be created or installed in `/usr/libexec/webmin/foobar`.

**Comment by jcameron** [comment]
Thanks, I'll fix these up. And yes, those locations are correct.

**Comment by jcameron** [comment]
> Suggest Changes still points to master and not main

What did you mean by this exactly?

**Comment by shoulders** [comment]
Hi

On the page `https://webmin.com/docs/development/creating-modules/` the suggestion link is wrong (might be the case on all other pages)

![image](https://github.com/user-attachments/assets/21b8bb64-309c-49ee-bb0c-4ac9cf203a3a)

it points to: `https://github.com/webmin/webmin.com/tree/master/content/docs/Development/creating-modules.md`

and should point to:
`https://github.com/webmin/webmin.com/tree/main/content/docs/Development/creating-modules.md`
or
`https://github.com/webmin/webmin.com/blob/main/content/docs/Development/creating-modules.md`

> notice the **master** --> **main** change

**Comment by iliaross** [comment]
Thanks for pointing this out! We will fix it on the next `webmin.com` rebuild.
