### ISSUE TITLE
FAQ Apache ProxyPass with subdirectory unclear

### ISSUE THREAD

**Issue by FalcoGer** [webmin/webmin.com#3]
I want to use apache to access webmin with a subdirectory and I have read the FAQ. The FAQ is very clear about how to do it with a virtual host with a subdomain, but the section about the subdirectory is very confusing because it refers to the subdomain and just says "edit this and add that on top of it". In particular I'm confused about what I should put into the apache virtual host configuration.

It would be better if it were written in the same style as the subdomain section, making it clear what to do without needing to cross reference and piece things together for each file that needs editing.

**Comment by jcameron** [comment]
What it means is, the Apache config should be like : 

```
<VirtualHost 1.2.3.4:443>
   ServerName webmin.example.com

   # Enable the usage of the SSL/TLS protocol engines
   SSLEngine on
   SSLProxyEngine on

   # Point to files with SSL certificates for virtual host
   SSLCertificateFile /etc/ssl/domains/example.com/ssl.combined
   SSLCertificateKeyFile /etc/ssl/domains/example.com/ssl.key
   
   # Use only secure version of the TLS protocol (TLSv1.3)
   SSLProtocol         all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2
   SSLHonorCipherOrder off
   SSLSessionTickets   off

   # Disables the remote server certificate checks
   # (only needed for self-signed certificates)
   SSLProxyCheckPeerCN     off
   SSLProxyCheckPeerName   off
   SSLProxyCheckPeerExpire off

   # Disable proxying for all /.well-known requests. It will 
   # only be useful, if a domain has "DocumentRoot" defined
   ProxyPass /.well-known !

   # Proxying both HTTP and websockets at the same time,
   # where the websockets URL's are not websocket-only
   # or not known in advance
   ProxyPass /webmin/ https://localhost:10000/
   RewriteEngine on
   RewriteCond %{HTTP:Upgrade} websocket [NC]
   RewriteCond %{HTTP:Connection} upgrade [NC]
   RewriteRule ^/webmin/?(.*) "wss://localhost:10000/$1" [P,L]
</VirtualHost>
```

**Comment by FalcoGer** [comment]
Yes, I figured it out eventually, but it was more confusing than it needed to be.

**Comment by jcameron** [comment]
Would it be clearer if the docs for sub-directory mode just contained the entire config like I posted above?

**Comment by FalcoGer** [comment]
> Would it be clearer if the docs for sub-directory mode just contained the entire config like I posted above?

It would be nice if it were written in the same manner as the subdomain section, so yes.

**Comment by jcameron** [comment]
Sure, I'll do that.

**Comment by iliaross** [comment]
Alright, I have also updated Nginx instructions in similar way.

@FalcoGer Thanks for the heads up!
