### ISSUE TITLE
setup-repos.sh: warn users before clearing the cache

### ISSUE THREAD

**Issue by hiarcs** [webmin/webmin.com#4]
setup-repos.sh will clean repo cache: line 64 # Setup OS dependent
Since some users may want to keep the downloaded packages from other repos in the dnf/yum cache, so if clearing the cache is necessary, it's better to warn the user before cleaning repo data.

**Comment by jcameron** [comment]
@iliaross do we really need to clear the repo cache when setting up new repositories?

**Comment by iliaross** [comment]
No, we don't need to do it.

**Comment by jcameron** [comment]
I will remove this from setup-repos.sh then

**Comment by iliaross** [comment]
Hold on, we still need to clean for Debian.
