### ISSUE TITLE
The Suggest Change link on Webmin 2.101 Changelog gives 404 error

### ISSUE THREAD

**Issue by verne-work** [webmin/webmin.com#8]
very recently webmin 2.101 and usermin 2.001 were announced, and the homepage has this link

https://webmin.com/changelog/webmin-2.101-and-usermin-2.001-released/

on that page it has a Suggest Change link -- which does not work  :-)

The similar link for the webmin 2.100 announcement two weeks ago also does not work, but the older virtualmin 7.7 link from April is working, as well as the webmin 2.021 link in March is working.

**Comment by iliaross** [comment]
Thanks for the heads up! Fixed now!

We need to automate the repo syncs!
