### ISSUE TITLE
virtualmin compatibility

### ISSUE THREAD

**Issue by verne-work** [webmin/webmin.com#9]
more of a comment than an issue --- maybe the problems with virtualmin with webmin 2.100 recently was a rare one-off occurrence -- as staff over at forums.virtualmin.com said that 2.100 was not 'ready' for virtualmin usage -- we were told to wait for a future release and now 2.101 is 'blessed' for usage with virtualmin.

so I was wondering if, and I know this is a big ask -- if the virtualmin staff can review pending releases of webmin to be sure they are compatible.

and/or -- have the webmin release notes clearly state either:    this version will work with virtualmin xx.xx   -- or say this version has yet to be reviewed/approved for virtualmin -- or go so far as to say this version will NOT work with virtualmin.

so there is some clear indication someplace about the virtualmin compatibility.

as you will recall, virtualmin has its own repos and over in the virtualmin forums we have been reminded several times to only use the virtualmin repo for virtualmin/webmin/usermin downloads  :smile:     So it can be confusing when on various other places we see something like --- HEY webmin 2.100 is out  -- but its 'missing' from the virtualmin repo.

again I know, especially for free software, this is a big ASK --- and can certainly understand if the current way of doing things is the best that can be done -- I know each have your own development teams !!   And/or the issue (not sure what it was) with 2.100 and virtualmin was a very rare issue and doubtful to happen again any time soon.

respectfully,

Verne

**Comment by iliaross** [comment]
Hello, Verne. Thanks for the heads up!

> if the virtualmin staff can review pending releases of webmin to be sure they are compatible.

Virtualmin and Webmin staff are the same people!



> and/or -- have the webmin release notes clearly state either: this version will work with virtualmin xx.xx -- or say this version has yet to be reviewed/approved for virtualmin -- or go so far as to say this version will NOT work with virtualmin.

Not ready doesn't mean it wouldn't work. We may simply wait it baking ...



> as you will recall, virtualmin has its own repos and over in the virtualmin forums we have been reminded several times to only use the virtualmin repo for virtualmin/webmin/usermin downloads 😄 So it can be confusing when on various other places we see something like --- HEY webmin 2.100 is out -- but its 'missing' from the virtualmin repo.

Different repos have different packages. There is not much we can do about it.
